const express=require("express");
const protect=require("../middleware/authMiddleware");
const authorizeRoles=require("../middleware/roleMiddleware");
const Consultation=require("../models/Consultation");
const createNotification=require("../utils/createNotification");
const router=express.Router();
router.get("/",protect,authorizeRoles("admin"),async(req,res)=>{try{const consultations=await Consultation.find().populate("patient","firstName lastName email").populate("physio","firstName lastName email").sort({date:1,createdAt:-1});const stats={total:consultations.length,scheduled:consultations.filter(x=>x.status==="Scheduled").length,completed:consultations.filter(x=>x.status==="Completed").length,cancelled:consultations.filter(x=>x.status==="Cancelled").length};res.json({success:true,consultations,stats});}catch(e){res.status(500).json({success:false,message:"Unable to fetch admin appointments"});}});
router.patch("/:id/status",protect,authorizeRoles("admin"),async(req,res)=>{try{const {status}=req.body;if(!["Scheduled","Completed","Cancelled"].includes(status))return res.status(400).json({success:false,message:"Invalid appointment status"});const consultation=await Consultation.findByIdAndUpdate(req.params.id,{status},{new:true,runValidators:true}).populate("patient","firstName lastName email").populate("physio","firstName lastName email");if(!consultation)return res.status(404).json({success:false,message:"Appointment not found"});
await createNotification({recipient:consultation.patient,sender:req.user.userId,type:"Consultation",title:`Appointment ${status.toLowerCase()}`,message:`Your appointment \"${consultation.title}\" is now ${status.toLowerCase()}.`,link:"/patient/consultations"});
res.json({success:true,consultation});}catch(e){res.status(500).json({success:false,message:"Unable to update appointment status"});}});
module.exports=router;